# Generated by Django 5.1.5 on 2025-12-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escan', '0005_alter_storevalidation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shippingrule',
            name='base_fee',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
